CREATE TABLE IF NOT EXISTS customer(
    id INT PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS admin(
    id INT PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS product(
    id INT PRIMARY KEY,
    category VARCHAR(32) NOT NULL,
    name VARCHAR(128) NOT NULL UNIQUE,
    price DECIMAL(21,4) NOT NULL,
    stock INT DEFAULT 0,
    status VARCHAR(21) DEFAULT 'AVAILABLE',
    creator VARCHAR(64) NOT NULL,
    updater VARCHAR(64),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS deal(
    id INT PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    policy VARCHAR(255) NOT NULL,
    apply_order INT NOT NULL UNIQUE,
    stackable BOOLEAN NOT NULL,
    creator VARCHAR(64) NOT NULL,
    updater VARCHAR(64),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO admin(id, name, password) VALUES(1, 'admin','$2a$10$FFl5kHqw3fIOdbTuHppmKOf1C7uVyqW.tWokYHSboyh3l3UZuKPd.');